import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt, pyqtSignal, QTimer

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 305)
        MainWindow.setFixedSize(350, 305)       # 设置窗体固定大小
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FilesButton = QtWidgets.QPushButton(self.centralwidget)
        self.FilesButton.setGeometry(QtCore.QRect(10, 10, 61, 23))
        self.FilesButton.setObjectName("FilesButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.FilesName = QtWidgets.QLabel(self.centralwidget)
        self.FilesName.setGeometry(QtCore.QRect(170, 10, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FilesName.setFont(font)
        self.FilesName.setText("")
        self.FilesName.setObjectName("FilesName")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 50, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 50, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.NumA = QtWidgets.QLabel(self.centralwidget)
        self.NumA.setGeometry(QtCore.QRect(40, 50, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumA.setFont(font)
        self.NumA.setText("")
        self.NumA.setObjectName("NumA")
        self.NumT = QtWidgets.QLabel(self.centralwidget)
        self.NumT.setGeometry(QtCore.QRect(120, 50, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumT.setFont(font)
        self.NumT.setText("")
        self.NumT.setObjectName("NumT")
        self.NumG = QtWidgets.QLabel(self.centralwidget)
        self.NumG.setGeometry(QtCore.QRect(200, 50, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumG.setFont(font)
        self.NumG.setText("")
        self.NumG.setObjectName("NumG")
        self.NumC = QtWidgets.QLabel(self.centralwidget)
        self.NumC.setGeometry(QtCore.QRect(280, 50, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumC.setFont(font)
        self.NumC.setText("")
        self.NumC.setObjectName("NumC")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 80, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.NumAT = QtWidgets.QLabel(self.centralwidget)
        self.NumAT.setGeometry(QtCore.QRect(70, 80, 55, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumAT.setFont(font)
        self.NumAT.setText("")
        self.NumAT.setObjectName("NumAT")
        self.NumCG = QtWidgets.QLabel(self.centralwidget)
        self.NumCG.setGeometry(QtCore.QRect(230, 80, 55, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumCG.setFont(font)
        self.NumCG.setText("")
        self.NumCG.setObjectName("NumCG")
        self.NumAT_2 = QtWidgets.QLabel(self.centralwidget)
        self.NumAT_2.setGeometry(QtCore.QRect(180, 80, 55, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumAT_2.setFont(font)
        self.NumAT_2.setText("")
        self.NumAT_2.setObjectName("NumAT_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 140, 330, 140))
        self.textBrowser.setFontPointSize(12)
        self.textBrowser.setObjectName("textBrowser")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.FilesButton.clicked.connect(self.operation)        # 设置点击事件
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.ProjectPath = os.getcwd()  # 获取当前工程文件位置

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基因测算"))
        self.FilesButton.setText(_translate("MainWindow", "选择文件"))
        self.label.setText(_translate("MainWindow", "当前文件："))
        self.label_2.setText(_translate("MainWindow", " A："))
        self.label_3.setText(_translate("MainWindow", " T："))
        self.label_4.setText(_translate("MainWindow", " G："))
        self.label_5.setText(_translate("MainWindow", " C："))
        self.label_6.setText(_translate("MainWindow", " A + T："))
        self.label_7.setText(_translate("MainWindow", " G + C："))
        self.label_8.setText(_translate("MainWindow", "完整序列："))

    def operation(self):
        fileName_choose, filetype = QFileDialog.getOpenFileName(None,"选择文件",self.ProjectPath,"Fasta Files (*.fasta);;Text Files (*.txt);;All Files (*)")   # 设置文件扩展名过滤,用双分号间隔
        if fileName_choose == "":       #未选择文件
            print("\n取消选择")
            return
        f = open(fileName_choose)
        ls = []
        for line in f:
                if not line.startswith('>'):
                            ls.append(line.replace('\n', ''))  # 去掉行尾的换行符真
        f.close()
        A = C = T = G = 0
        DNA_str = ''
        for i in range(0, len(ls)):
                DNA_str += ls[i]
        A += DNA_str.count('A')
        C += DNA_str.count('C')
        T += DNA_str.count('T')
        G += DNA_str.count('G')
        CG = round((G + C) / (A + T + C + G) * 100,2)
        AT = round((A + T) / (A + T + C + G) * 100,2)
        FileName = fileName_choose.split('/')

        self.FilesName.setText(FileName[-1])
        self.textBrowser.setText(str(DNA_str))
        self.NumA.setText(str(A))
        self.NumT.setText(str(T))
        self.NumG.setText(str(G))
        self.NumC.setText(str(C))
        self.NumAT.setText("%s%%"%str(AT))
        self.NumCG.setText("%s%%"%str(CG))




if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
